-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Area"
(
    id bigint NOT NULL,
    nome character varying,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Mes"
(
    id character varying NOT NULL,
    numero bigint NOT NULL,
    id_ano bigint,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ano
(
    id bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.mud_temp
(
    id bigint NOT NULL,
    mud_value double precision,
    desvio_padrao double precision,
    id_area bigint NOT NULL,
    id_mes character varying NOT NULL,
    id_ano bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.geracao_energia
(
    id bigint NOT NULL,
    valor double precision,
    id_area bigint NOT NULL,
    id_ano bigint NOT NULL,
    id_tipo bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Tipo_energia"
(
    id bigint NOT NULL,
    valor character varying,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Pais"
(
    id bigint NOT NULL,
    codigo character varying,
    nome character varying,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Grupo"
(
    id bigint NOT NULL,
    codigo character varying,
    nome character varying,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Pais_Grupo"
(
    "Pais_id" bigint NOT NULL,
    "Grupo_id" bigint NOT NULL
);

ALTER TABLE IF EXISTS public."Mes"
    ADD FOREIGN KEY (id_ano)
    REFERENCES public.ano (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.mud_temp
    ADD FOREIGN KEY (id_area)
    REFERENCES public."Area" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.mud_temp
    ADD FOREIGN KEY (id_mes)
    REFERENCES public."Mes" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.mud_temp
    ADD FOREIGN KEY (id_ano)
    REFERENCES public.ano (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.geracao_energia
    ADD FOREIGN KEY (id_area)
    REFERENCES public."Area" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.geracao_energia
    ADD FOREIGN KEY (id_ano)
    REFERENCES public.ano (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.geracao_energia
    ADD FOREIGN KEY (id_tipo)
    REFERENCES public."Tipo_energia" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Pais"
    ADD FOREIGN KEY (id)
    REFERENCES public."Area" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Grupo"
    ADD FOREIGN KEY (id)
    REFERENCES public."Area" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Pais_Grupo"
    ADD FOREIGN KEY ("Pais_id")
    REFERENCES public."Pais" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Pais_Grupo"
    ADD FOREIGN KEY ("Grupo_id")
    REFERENCES public."Grupo" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;