-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."AREA"
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    nome character varying,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."MES"
(
    id character varying NOT NULL,
    numero bigint NOT NULL,
    id_ano bigint,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."ANO"
(
    id bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."MUD_TEMP"
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    mud_value double precision,
    desvio_padrao double precision,
    id_area bigint NOT NULL,
    id_mes character varying NOT NULL,
    id_ano bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."GERACAO_ENERGIA"
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    valor double precision,
    id_area bigint NOT NULL,
    id_ano bigint NOT NULL,
    id_tipo bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."TIPO_ENERGIA"
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    valor character varying,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."PAIS"
(
    id bigint NOT NULL,
    codigo character varying,
    nome character varying,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."GRUPO"
(
    id bigint NOT NULL,
    codigo character varying,
    nome character varying,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Pais_Grupo"
(
    "Pais_id" bigint NOT NULL,
    "Grupo_id" bigint NOT NULL
);

ALTER TABLE IF EXISTS public."MES"
    ADD FOREIGN KEY (id_ano)
    REFERENCES public."ANO" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."MUD_TEMP"
    ADD FOREIGN KEY (id_area)
    REFERENCES public."AREA" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."MUD_TEMP"
    ADD FOREIGN KEY (id_mes)
    REFERENCES public."MES" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."MUD_TEMP"
    ADD FOREIGN KEY (id_ano)
    REFERENCES public."ANO" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."GERACAO_ENERGIA"
    ADD FOREIGN KEY (id_area)
    REFERENCES public."AREA" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."GERACAO_ENERGIA"
    ADD FOREIGN KEY (id_ano)
    REFERENCES public."ANO" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."GERACAO_ENERGIA"
    ADD FOREIGN KEY (id_tipo)
    REFERENCES public."TIPO_ENERGIA" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PAIS"
    ADD FOREIGN KEY (id)
    REFERENCES public."AREA" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."GRUPO"
    ADD FOREIGN KEY (id)
    REFERENCES public."AREA" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Pais_Grupo"
    ADD FOREIGN KEY ("Pais_id")
    REFERENCES public."PAIS" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Pais_Grupo"
    ADD FOREIGN KEY ("Grupo_id")
    REFERENCES public."GRUPO" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;