-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."AREA"
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nome character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "AREA_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."GERACAO_ENERGIA"
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    unidade_geracao character varying(10) COLLATE pg_catalog."default",
    valor_geracao double precision,
    unidade_emissao character varying(10) COLLATE pg_catalog."default",
    valor_emissao double precision,
    ano bigint NOT NULL,
    id_area bigint NOT NULL,
    id_tipo bigint NOT NULL,
    CONSTRAINT "GERACAO_ENERGIA_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."GRUPO"
(
    id bigint NOT NULL,
    codigo character varying(10) COLLATE pg_catalog."default" NOT NULL,
    nome character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "GRUPO_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."MUD_TEMP"
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    mud_value double precision,
    desvio_padrao double precision,
    ano bigint NOT NULL,
    mes bigint COLLATE pg_catalog."default" NOT NULL,
    id_area bigint NOT NULL,
    CONSTRAINT "MUD_TEMP_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."PAIS"
(
    id bigint NOT NULL,
    codigo character varying(10) COLLATE pg_catalog."default" NOT NULL,
    nome character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PAIS_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."PAIS_GRUPO"
(
    "Pais_id" bigint NOT NULL,
    "Grupo_id" bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS public."TIPO_ENERGIA"
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    valor character varying(50) COLLATE pg_catalog."default",
    renovavel boolean,
    CONSTRAINT "TIPO_ENERGIA_pkey" PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."GERACAO_ENERGIA"
    ADD CONSTRAINT "GERACAO_ENERGIA_id_area_fkey" FOREIGN KEY (id_area)
    REFERENCES public."AREA" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."GERACAO_ENERGIA"
    ADD CONSTRAINT "GERACAO_ENERGIA_id_tipo_fkey" FOREIGN KEY (id_tipo)
    REFERENCES public."TIPO_ENERGIA" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."GRUPO"
    ADD CONSTRAINT "GRUPO_id_fkey" FOREIGN KEY (id)
    REFERENCES public."AREA" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "GRUPO_pkey"
    ON public."GRUPO"(id);


ALTER TABLE IF EXISTS public."MUD_TEMP"
    ADD CONSTRAINT "MUD_TEMP_id_area_fkey" FOREIGN KEY (id_area)
    REFERENCES public."AREA" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PAIS"
    ADD CONSTRAINT "PAIS_id_fkey" FOREIGN KEY (id)
    REFERENCES public."AREA" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "PAIS_pkey"
    ON public."PAIS"(id);


ALTER TABLE IF EXISTS public."PAIS_GRUPO"
    ADD CONSTRAINT "PAIS_GRUPO_Grupo_id_fkey" FOREIGN KEY ("Grupo_id")
    REFERENCES public."GRUPO" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PAIS_GRUPO"
    ADD CONSTRAINT "PAIS_GRUPO_Pais_id_fkey" FOREIGN KEY ("Pais_id")
    REFERENCES public."PAIS" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;